config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  devise_for :users
  root "places#index"
  resources :places do
    resources :reviews
  end
  resources :categories
  resources :users, :only => [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    can :read, Place
    can :read, Category

    if user.present?
      can :create, Place
      can :edit, Place, user_id: user.id
      can :destroy, Place, user_id: user.id
      if user.admin?
        can :manage, :all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { maximum: 250 }
  has_many :places
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :picture
  has_many :reviews
  self.per_page = 20

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :place
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :places
  has_many :reviews
  has_one_attached :picture

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to root_path, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
      redirect_to root_path, :alert => exception.message
    end
  end


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # load_and_authorize_resource
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def destroy
    Category.destroy(params[:id])
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  load_and_authorize_resource
  def index
    @places  = Place.paginate(page: params[:page])
  end

  def new
    @place = Place.new()
  end

  def show
    @place = Place.find(params[:id])
  end

  def create
    @place = current_user.places.build(place_params)
    if @place.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def upload_picture
    @place.picture.attach(uploaded_file) if uploaded_file.present?
  end

  def uploaded_file
    params[:place][:picture]
  end

  def update
    @place = Place.find(params[:id])
    if @place.update(place_params)
      redirect_to @place
    else
      render 'edit'
    end
  end


  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:title, :description, :category_id, :picture, :search)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show

  end

  def upload_picture
    @place.picture.attach(uploaded_file) if uploaded_file.present?
  end

  def uploaded_file
    params[:place][:pictures]
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
  <%= f.input :name, label: 'Title' %>
  <%= f.submit 'Create', :class => "btn btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= render 'form' %>
      <br>
      <%= link_to "Edit category", category_path(@category), :class => "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
<h1>Categories</h1>
  <% if can? :create, Category %>
    <p>
        <%= link_to "Add Category", new_category_path, class: 'btn btn-success' %>
    </p>
  <% end %>

  <table class="table table-striped">
  <tr>
    <th>Name</th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <% if can? :destroy, category  %>
        <%= link_to 'Delete', place_path(place), method: :delete, data: {confirm: 'Are you sure'} %>
      <% end %>
    </tr>
  <% end %>
</table>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= render 'form' %>
      <br>
      <%= link_to "Back", root_path , :class => "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Places</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        &#x2630;
      </button>

      <%= link_to 'All places', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%= link_to 'Categories', categories_path, class: 'navbar-brand' %>
          </li>
          <li class="nav-item"><a href="#" class="nav-link">Contacts</a>
          </li>
        </ul>
        <div class="navbar-nav ml-auto">
          <div>
           <%= link_to 'Sign in', new_user_session_path, class: 'navbar-brand' %>
          </div>
          <% if user_signed_in? %>
            <div class="nav-item">
                <span class="navbar-text">
                  Hello, &nbsp;
                </span>
            </div>
            </div>


            <div class="dropdown show">
              <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </div>
              <div>
          <% end %>
          </div>
          </div>
          </div>
    </div>

  </nav>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= simple_form_for @place do |f| %>
  <%= f.input :title, label: 'Title' %>
  <%= f.input :description, label: 'Description' %> <br />
  <p>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </p> <br />
  <%= f.file_field :picture %><br />
  <%= f.submit 'Create', :class => "btn btn-primary" %>
<% end %>

app/views/places/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= render 'form' %>
      <br>
      <%= link_to "Back", root_path(@place), :class => "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/places/index.html.erb
 <p>
    <% if can? :create, Place %>
      <%= link_to "New Place", new_place_path, class: 'btn btn-success' %>
    <% end %>
  </p>
  <table class="table table-striped">

    <tr>
      <th>Title:</th>
      <th>Picture: </th>
      <th>Description:</th>
      <th>Author:</th>
      <th>Category:</th>
      <th>Actions:</th>
    </tr>

    <% @places.each do |place| %>
      <tr>
        <td> <%= link_to "#{place.title}", place_path(place)  %></td>
        <td>

          <% if place.picture.attached? %>
          <%= image_tag place.picture, size: 100 %>
          <% end %>
        </td>
        <td><%= place.description %></td>
        <td><%= link_to "#{place.user.name}", user_path(place.user.id) %></td>
        <td><%= place.category.name %></td>
        <td>
          <%= link_to 'View', place_path(place) %>
          <% if can? :edit, place  %>
            <%= link_to 'Edit', edit_place_path(place) %>
          <% end %>
          <% if can? :destroy, place  %>
            <%= link_to 'Delete', place_path(place), method: :delete,
                        data: {confirm: 'Are you sure'} %>
          <% end %>
        </td>
      </tr>

    <% end %>

  </table>
  <br />
  <div class="pagination pagination-sm">
    <%= will_paginate @places, :container => false %>
  </div>
  <br />

app/views/places/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= render 'form' %>
      <br>
      <%= link_to "Back", root_path(@place), :class => "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <p id="notice"><%= notice %></p>
      <p>Title: <%= @place.title %></p>
      <p>Picture:
        <% if @place.picture.attached? %>
          <%= image_tag @place.picture, size: 650 %>
        <% end %>
      </p>
      <p>Category: <%= @place.category.name %></p>
      <p>Description: <%= @place.description%></p>
      <p>Author: <%= @place.user.name %></p>
      <br>
      <% if can? :edit, @place %>
        <%= link_to "Edit", edit_place_path(@place) %>
      <% end %>
      <%= link_to "Back", root_path %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<h2>My places</h2>